import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import bcrypt from "bcryptjs";
import { CATEGORIES } from "../prisma/seed-data";

function shortId(prefix: string, seed: string): string {
  const hash = createHash("sha1").update(seed).digest("hex").slice(0, 20);
  return `${prefix}_${hash}`;
}

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBool(value: boolean): string {
  return value ? "1" : "0";
}

async function main() {
  const lines: string[] = [
    "-- Generated by scripts/generate-d1-seed.ts - do not edit by hand.",
    "-- Re-run `npm run cf:seed:gen` after changing prisma/seed-data.ts.",
    "",
  ];

  CATEGORIES.forEach((cat, catIndex) => {
    const categoryId = shortId("cat", cat.name);
    lines.push(
      `INSERT OR IGNORE INTO "Category" ("id", "name", "order", "createdAt", "updatedAt") VALUES (${sqlString(
        categoryId
      )}, ${sqlString(cat.name)}, ${catIndex}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`
    );

    cat.items.forEach((item, itemIndex) => {
      const itemId = shortId("item", `${cat.name}:${item.name}`);
      lines.push(
        `INSERT OR IGNORE INTO "MenuItem" ("id", "name", "description", "categoryId", "productCost", "saladCost", "oldPrice", "newPrice", "isOffer", "offerNote", "active", "order", "createdAt", "updatedAt") VALUES (${sqlString(
          itemId
        )}, ${sqlString(item.name)}, ${sqlString(item.description)}, ${sqlString(
          categoryId
        )}, ${item.productCost}, ${item.saladCost}, ${item.oldPrice}, ${item.newPrice}, ${sqlBool(
          item.isOffer ?? false
        )}, ${sqlString(item.offerNote)}, 1, ${itemIndex}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`
      );
    });
  });

  lines.push(
    `INSERT OR IGNORE INTO "Settings" ("id", "siteName", "tagline", "updatedAt") VALUES ('main', ${sqlString(
      "خان الجمر"
    )}, ${sqlString("سيّد المشويات التركية")}, CURRENT_TIMESTAMP);`
  );

  const adminUsername = process.env.ADMIN_USERNAME || "admin";
  const adminPassword = process.env.ADMIN_PASSWORD || "changeme123";
  const passwordHash = await bcrypt.hash(adminPassword, 10);
  const adminId = shortId("admin", adminUsername);

  lines.push(
    `INSERT OR IGNORE INTO "AdminUser" ("id", "username", "passwordHash", "createdAt") VALUES (${sqlString(
      adminId
    )}, ${sqlString(adminUsername)}, ${sqlString(passwordHash)}, CURRENT_TIMESTAMP);`
  );

  const outputPath = join(__dirname, "..", "migrations", "0002_seed_data.sql");
  writeFileSync(outputPath, lines.join("\n") + "\n", "utf-8");

  console.log(`Wrote ${outputPath}`);
  if (!process.env.ADMIN_PASSWORD) {
    console.warn(
      "WARNING: generated with default admin password 'changeme123'. Set ADMIN_PASSWORD before generating for production, e.g.:\n" +
        "  ADMIN_PASSWORD='your-strong-password' npm run cf:seed:gen"
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
